name: Main

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build Blackprint Modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ⚙ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 🔃 Setup PNPM modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - run: pnpm i -g @blackprint/cli-tools@0.3

      - name: 🛠 Compiling Blackprint
      - run: blackprint build production

      # ToDo, add Blackprint node testing (for Browser/Node.js/Deno)

      - name: 📦 Release
        uses: softprops/action-gh-release@v1
        # GitHub releases requires a tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          files: |
            dist/**/*
            src/**/*
            blackprint.config.js
            package.json
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
